[build]
  command = "yarn build"
  publish = "dist"

[dev]
  command = "yarn dev"
  framework = "#custom"
  port = 8888
  targetPort = 3000
  autoLaunch = false

[functions]
  directory = "functions/"